// homes
export const FETCH_ALL_HOMES_REQUEST = "FETCH_ALL_HOMES_REQUEST";
export const FETCH_ALL_HOMES_RESULT = "FETCH_ALL_HOMES_RESULT";
// auth
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_RESULT = "REGISTER_USER_RESULT";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_RESULT = "LOGIN_USER_RESULT";
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_RESULT = "LOGOUT_USER_RESULT";
